var emotionUrl = {
	"[Smile]": "/res/chatBox/emotion/Expression_1.png",
	"[Joyful]": "/res/chatBox/emotion/Expression_2.png",
	"[Blank Faces]": "/res/chatBox/emotion/Expression_3.png",
	"[Stuck-Out Tongue Faces]": "/res/chatBox/emotion/Expression_4.png",
	"[Cold Sweat]": "/res/chatBox/emotion/Expression_5.png",
	"[Smiling Face With Sunglasses]": "/res/chatBox/emotion/Expression_6.png",
	"[Pirate Face]": "/res/chatBox/emotion/Expression_7.png",
	"[Angry]": "/res/chatBox/emotion/Expression_8.png",
	"[Crying]": "/res/chatBox/emotion/Expression_9.png",
	"[Kissing]": "/res/chatBox/emotion/Expression_10.png",
	"[Devil]": "/res/chatBox/emotion/Expression_11.png",
	"[Smiling Face With Heart-Shaped Eyes]": "/res/chatBox/emotion/Expression_12.png",
	"[Smiling Face With Smiling Eyes]": "/res/chatBox/emotion/Expression_13.png",
	"[Sick]": "/res/chatBox/emotion/Expression_14.png",
	"[Loudly Crying]": "/res/chatBox/emotion/Expression_15.png",
	"[Puke]": "/res/chatBox/emotion/Expression_16.png",
	"[Dizzy]": "/res/chatBox/emotion/Expression_17.png",
	"[Smirking]": "/res/chatBox/emotion/Expression_18.png",
	"[Nerd]": "/res/chatBox/emotion/Expression_19.png",
	"[Whistle]": "/res/chatBox/emotion/Expression_20.png",
	"[Nauseated]": "/res/chatBox/emotion/Expression_21.png",
	"[Grinning]": "/res/chatBox/emotion/Expression_22.png",
	"[Slight]": "/res/chatBox/emotion/Expression_23.png",
	"[Winking]": "/res/chatBox/emotion/Expression_24.png",
	"[Beaten Face]": "/res/chatBox/emotion/Expression_25.png"
};