/*
 * 英文、法文  语音数据文件
 */


var LANGUAGE = {
	french: {
		LOGIN: "s'identifier",
		SIGN_UP: "s'inscrire",
		SIGN_IN: "signe",
		Email: 'Email',
		Password: 'mot de passe',
		ReEnterPassword: "Retaper le mot de passe",
		ForgotPassword: 'mot de passe oublié?',
		LoginWith: 'Connectez-vous avec',
		loginPolicy: 'Inscrivez-vous en un clic, vous acceptez nos termes de service et la politique de confidentialité',
		FIRST_NAME: 'prénom',
		LAST_NAME: "nom de famille",
		BIRTHDAY: 'anniversaire',
		SEND: 'Envoyer le code',
		RESEND: 'renvoyer le code',
		CONTINUE: 'Continuer',
		CONFIRM: 'Confirmer',
		AvaliableFunds: 'Fonds Disponibles',
		Notifications: 'Notifications',
		Revenue: 'Revenu',
		Ratings: 'Notes',
		Favorites: 'Favoris',
		PaymentMethod: 'Mode de paiement',
		ThankYou: 'Merci',
		NewPassword: 'Nouveau mot de passe',
		ConfirmNewPassword: 'Confirmer le nouveau mot de passe',
		registerPolicy: "En appuyant sur S'inscrire vous acceptez nos Conditions d'Utilisation et Politique de Confidentialité.",
		Male: 'des hommes',
		Female: 'les femmes',
		Discovering: 'Découverte',
		AllFavors: 'Toutes les faveurs',
		browse: 'Naviguer',
		Browse: 'Naviguer',
		Inbox: 'Messagerie',
		inbox: 'boîte de réception',
		Post: 'Post',
		post: 'post',
		My_Favors: 'Mes Favoris',
		MyFavors: 'MesFavoris',
		myFavors: 'myFavors',
		more: 'plus',
		More: 'Plus',
		Settings: 'Paramètres',
		InviteFriends: 'Inviter des amis',
		TermsPolicy: 'Termes et politique',
		ContactUs: 'Contactez nous',
		LogOut: 'Déconnexion',
		Completed: 'Terminé',
		Ongoing: 'En cours',
		Open: 'Ouvrir',
		About: 'Sur',
		Reviews: 'Avis',
		Verifications: 'Vérifications',
		Skills: 'Compétences',
		AsAPoster: 'En tant que poster',
		AsAHelper: "En tant qu'assistant",
		AsAHelper2: 'assistant',
		AsAPoster2: 'poster',
		ViewAllReviews: 'Voir tous les commentaires',
		ChangePassword: 'Changer le mot de passe',
		Language: 'La langue',
		CurrentPassword: 'Mot de passe actuel',
		SAVE: 'Sauver',
		HowCanWeHelpYou: 'Comment pouvons-nous vous aider?',
		AreYouSureToLogout: 'Êtes-vous sûr de vouloir vous déconnecter?',
		No: 'Non',
		Yes: 'Oui',
		AddNewCreditCard: 'ajouter une nouvelle carte de crédit',
		Name: 'prénom',
		Card_number: 'numéro de carte',
		ExpireDate: "date d'expiration",
		SecurityCode: 'code de sécurité',
		StreetAddress: 'adresse de rue',
		City: 'ville',
		Province: 'Province',
		PostalCode: 'code postal',
		AddCreditCardTip: 'Afavor maintiendra la confidentialité de vos informations',
		ADD_CREDIT_CARD: 'AJOUTER VOTRE CARTE DE CREDIT',
		AddNewDebitCard: 'Ajouter une nouvelle Carte de Débit',
		TransitNumber: 'Numéro de transit',
		InsititutionNumber: "Numéro d'institut",
		SaveCardDetails: 'Enregistrer les détails de la carte',
		ADD_DEBIT_ACCOUNT: 'ajouter un compte de débit',
		CreditCard: 'Carte de crédit',
		Analytics: 'Analytique',
		DebitAccount: 'Compte de débit',
		Favors: 'Favoris',
		Helper: 'Assistant',
		EditProfile: 'Changer votre Profil',
		ReceivePayments: 'Recevoir des paiements',
		MakePayments: 'Effectuer des Paiements',
		Ratings: 'Notes',
		confirmEmailTip: 'Veuillez entrer le code de vérification que vous venez de recevoir sur votre adresse e-mail.',
		forgetPawdTip: 'Veuillez entrer votre adresse e-mail et nous allons vous envoyer un code de vérification.',
		EnterVerificationCode: 'Entrer le code de vérification',
		SKIP: 'sauter',
		GET_STARTED: 'commencez!',
		GENDER: 'sexe',
		thankYouTip: ',Votre faveur a été publié',
		thankYouTip2: ',Votre faveur a été envoyé',
		Make_A_Favor: 'Faire une faveur',
		youHaveNoReceivedAnyCommentsYet: "Vous n'avez pas encore reçu de commentaires.",
		Currency: 'Devise',
		YourEmailAddress: 'Votre adresse e-mail',
		TermsConditions: "Conditions d'Utilisation",
		PrivacyPolicy: 'Politique de Confidentialité',
		AccountNumber: 'Numéro de Compte',
		Loading: 'Chargement...',
		REMOVE_CARD: 'SUPPRIMER LA CARTE',
		Income: 'Revenu',
		Expenditure: 'Dépense',
		SetAsDefaultDebitCart: 'Définir comme carte de débit par défaut',
		WorkEnvironment: 'Environnement de travail',
		SUBMIT: 'Soumettre',
		Attitude: 'Attitude',
		Difficulty: 'Difficulté',
		Leave_A_Comment: 'Laissez un commentaire...',
		Ability: 'Capacité',
		Punctuality: 'Ponctualité',
		WorkQuality: 'qualité du travail',
		Communication: 'Communication',
		online: 'En ligne',
		Completed_by: 'Terminé par',
		FavorEarnings: 'Favoriser les gains',
		Price: 'Prix',
		TotalExpenditure: 'Total des dépenses',
		Online: 'En ligne',
		Comment: 'Commentaire',
		Comments: 'Commentaires',
		Offer: 'Offre',
		Offers: 'Offres',
		You_have_no_favorite_favor: "Vous n'avez pas de faveur préférée.",
		You_have_no_favorite_helper: "Vous n'avez aucune aide favorite.",
		There_is_no_content: "Il n'y a pas de compétition.",
		Everything: 'Tout',
		Avaliable_for_withdrawal: 'Disponible pour retrait',
		ThisFavor: 'Favoris',
		Me: 'Moi',
		AfavorFee: 'Frais de saveur',
		DateRange: 'Période',
		From: 'De',
		To: 'à',
		APPLY_NOW: 'Appliquer Maintenant',
		You_have_no_received_any_notifications_yet: "Vous n'avez reçu aucune notification pour le moment.",
		REQUEST_A_QUOTE: 'Demander un devis',
		Birthday: 'anniversaire',
		First_name: 'Prénom',
		Last_name: 'Nom de famille',
		You_have_no_received_any_ratings: "Vous n'avez reçu aucune note",
		Communication: 'Communication',
		FavorTitle: 'Titre de faveur',
		Title_of_favor: 'Titre de faveur',
		FavorDetails: 'Détails favorables',
		Describe_your_favor: 'Décrivez votre faveur',
		UploadAttachments: 'Télécharger des pièces jointes',
		DifficultyLevel: 'Niveau de difficulté',
		Pay_from_income_balance: 'Payer avec le solde des revenus',
		ApplePay: 'Apple pay',
		PayWithPayPal: 'Payer avec PayPal',
		DueDate: "Date d'échéance",
		Country: 'Pays',
		Offline: 'Hors ligne',
		How_can_this_favor_be_completed: 'Comment cette faveur peut-elle être complétée?',
		Person: 'Personne',
		EstimatedBudget: 'Budget estimé',
		Hourly: 'Toutes les heures',
		TotalFixPrice: 'Prix fixe total',
		Workers: 'Ouvriers',
		Please_fill_in_the_address: 'Veuillez renseigner votre adresse',
		Details: 'Détails',
		Location: 'Emplacement',
		Budget: 'Budget',
		Payment: 'Paiement',
		Delete: 'Supprimer',
		Reset: 'Réinitialiser',
		Please_fill_in_these_details_before_sending_an_offer: "veuillez remplir ces détails avant d'envoyer une offre",
		Provide_a_debit_account: 'Fournir un compte de débit',
		Enter_a_mobile_number: 'entrez un numéro de téléphone mobile',
		Provide_your_Date_of_Birth: 'Fournissez votre date de naissance',
		MobileNumbe: 'Numéro de téléphone mobile',
		Chat: 'Chat',
		Waiting: 'En attente',
		Address: 'Adresse',
		Ongoing_by: 'En cours',
		There_is_no_relevant_information: "Il n'y a pas d'informations pertinentes",
		Posted_by: 'Posté par',
		workers: 'ouvriers',
		worker: 'ouvrier',
		On_hold: 'En suspens',
		Cancel: 'Annuler',
		Due: "Date d'échéance",
		You_have_no_completed_favor: "Vous n'avez pas de service achevé",
		Attachments: 'pièces jointes',
		FavorLoction: 'Faveur loction',
		FavorType: 'Type de faveur',
		Both: 'Tous les deux',
		APPPLY_NOW: "S'INSCRIRE MAINTENANT",
		You_have_no_ongoing_favor: "Vous n'avez aucun service en cours",
		HelperList: 'Liste des assistants',
		There_is_no_helper: "Il n'y a pas d'assistant",
		Assigned: 'Attribué',
		AcceptOffer: "Accepter l'offre",
		ViewAllComments: 'Voir tous les commentaires',
		Reply: 'Répondre',
		Do_it_Now: 'Faites le maintenant',
		Quit: 'Quitter',
		Begin: 'Commencer',
		WaitingOffer: 'Offre en attente',
		You_have_no_posted_a_favor_yet: "Vous n'avez pas encore posté de service",
		FavorComplete: 'Service achevé',
		NoMessage: 'Pas de message',
		ShareWithYourFriends: 'Partagez avec vos amis',
		ShareWithYourFavouriteHelpers: 'Partagez avec vos assistants favoris',
		Report: 'Rapport',
		The_deleted_task_cannot_be_resumed: 'La tâche supprimée ne peut pas être reprise.',
		The_contents_have_not_been_saved: "Le contenu n'a pas été enregistré,",
		are_you_sure_to_exit: 'êtes-vous sûr de vouloir quitter ?',
		Now_you_have_two_options_to_deal_with_your_favor: 'Maintenant vous avez deux options pour traiter votre service',
		Hi: 'Salut',
		Your_favor_cost_will_be_deposited_to_your_balance: '(Vos frais de service seront ajoutés à votre solde)',
		REPOST: 'Partagée',
		DELETE: 'Supprimer',
		Are_you_sure_to_end_this_favor: 'Êtes-vous sûr de mettre fin à ce service?',
		No_relevant_content: '',
		Enter_a_new_address: 'Entrez une nouvelle adresse',
		BaseLocation: '',
		CurrenLoaction: '',
		SortBy: 'Trier par',
		Recent: 'Récent',
		Distance: 'Distance',
		Low: 'bas',
		High: 'élevé',
		Favor_within: 'Faveur dans',
		"Enter_the_ 6-dight_code": '',
		DONE: 'Terminé',
		Resend_code: 'Renvoyer le code',
		MobileNumber: 'numéro de téléphone mobile',
		SEND_CODE: 'Envoyer le code',
		Refresh: 'Rafraîchir',
		Please_take_a_clear_photo_of_your_face: 'Veuillez prendre une photo nette de votre visage',
		"Notice:_No_sunglasses_or_hats": '' ,
		'Notice:_This_photo_only_be_used_for_"As_a_Helper"_in_your_account': "Remarque: Cette photo ne peut être utilisée que pour \"En tant qu'assistant\" dans votre compte.",
		TAKE_PHOTO: 'PRENDRE UNE PHOTO',
		waiting_for_uploading: '',
		RETAKE: 'REPRENDRE',
		TAKE: 'PRENDRE',
		Please_provide_a_vaild_photo_ID: "Veuillez fournir une photo d'identité valide",
		"Driver's_Licence_Passport_Brith_Certificate_or_Residency_Card": '(Permis de conduire, passeport, certificat de naissance ou carte de résidence)',
		You_will_receive_notification_shortly_after_you_re_approved: 'Vous recevrez une notification peu après votre approbation',
		If_this_is_your_first_time_to_be_a_helper_in_this_app_please_provide_the_required_documents_below: "Si c'est votre première fois en tant qu'assistant dans cette application, veuillez fournir les documents requis ci-dessous.",
		ProfilePhoto: 'Photo de profil',
		Proof_of_Work_Eligbility: "Preuve d'admissibilité au travail",
		PhotoID: "Photo d'identité",
		Please_make_sure_your_document_is_centered_and_readable: '',
		Please_provide_a_Social_Insurance_Number_SIN_to_prove_your_work_eligibility: "Veuillez fournir un numéro d'assurance sociale (NAS) pour prouver votre admissibilité au travail",
		Set_as_default_debit_card: 'Définir comme carte de débit par défaut',
		Filters: 'Filtres'
	},
	english: {
		Filters: 'Filters',
		Set_as_default_debit_card: 'Set as default debit card',
		Please_provide_a_Social_Insurance_Number_SIN_to_prove_your_work_eligibility: 'Please provide a Social Insurance Number (SIN) to prove your work eligibility.',
		Please_make_sure_your_document_is_centered_and_readable: 'Please make sure your document is centered and readable.',
		PhotoID: 'Photo ID',
		Proof_of_Work_Eligbility: 'Proof of Work Eligbility',
		ProfilePhoto: 'Profile Photo',
		If_this_is_your_first_time_to_be_a_helper_in_this_app_please_provide_the_required_documents_below: 'If this is your first time to be a helper in this app, please provide the required documents below.',
		You_will_receive_notification_shortly_after_you_re_approved: "You will receive notification shortly after you're approved.",
		"Driver's_Licence_Passport_Brith_Certificate_or_Residency_Card": "(Driver's Licence, Passport, Brith Certificate, or Residency Card)",
		Please_provide_a_vaild_photo_ID: 'Please provide a vaild photo ID.',
		TAKE: 'TAKE',
		RETAKE: 'RETAKE',
		waiting_for_uploading: 'waiting for uploading...',
		TAKE_PHOTO: 'TAKE PHOTO',
		'Notice:_This_photo_only_be_used_for_"As_a_Helper"_in_your_account': '(Notice: This photo only be used for "As a Helper" in your account.)',
		"Notice:_No_sunglasses_or_hats": '(Notice: No sunglasses or hats)',
		Please_take_a_clear_photo_of_your_face: 'Please take a clear photo of your face.',
		Refresh: 'Refresh',
		SEND_CODE: 'SEND CODE',
		MobileNumber: 'Mobile Number',
		Resend_code: 'Resend code',
		DONE: 'DONE',
		"Enter_the_ 6-dight_code": 'Enter the 6-dight code',
		Favor_within: 'Favor within',
		High: 'High',
		Low: 'Low',
		Distance: 'Distance',
		Recent: 'Recent',
		SortBy: 'Sort By',
		CurrenLoaction: 'Current Loaction',
		BaseLocation: 'Base Location',
		Enter_a_new_address: 'Enter a new address',
		No_relevant_content: 'No relevant content.',
		Are_you_sure_to_end_this_favor: 'Are you sure to end this favor?',
		DELETE: 'DELETE',
		REPOST: 'REPOST',
		Your_favor_cost_will_be_deposited_to_your_balance: '(Your favor cost will be deposited to your balance)',
		Hi: 'Hi',
		Now_you_have_two_options_to_deal_with_your_favor: 'Now you have two options to deal with your favor.',
		are_you_sure_to_exit: 'are you sure to exit?',
		The_contents_have_not_been_saved: 'The contents have not been saved,',
		The_deleted_task_cannot_be_resumed: 'The deleted task cannot be resumed.',
		Report: 'Report',
		ShareWithYourFavouriteHelpers: 'Share With Your Favourite Helpers',
		ShareWithYourFriends: 'Share With Your Friends',
		NoMessage: 'No Message~',
		FavorComplete: 'Favor Complete',
		You_have_no_posted_a_favor_yet: 'You haven’t posted a favor yet.',
		WaitingOffer: 'Waiting Offer',
		Begin: 'Begin',
		Quit: 'Quit',
		Do_it_Now: 'Do it Now!',
		Reply: 'Reply',
		ViewAllComments: 'View All Comments',
		AcceptOffer: 'Accept Offer',
		Assigned: 'Assigned',
		There_is_no_helper: 'There is no helper.',
		HelperList: 'Helper List',
		You_have_no_ongoing_favor: 'You have no ongoing favor.',
		APPPLY_NOW: 'APPPLY NOW',
		Both: 'Both',
		FavorType: 'Favor Type',
		FavorLoction: 'Favor Loction',
		Attachments: 'Attachments',
		You_have_no_completed_favor: 'You have no completed favor.',
		Due: 'Due',
		Cancel: 'Cancel',
		On_hold: 'On hold',
		workers: 'workers',
		worker: 'worker',
		Posted_by: 'Posted by',
		There_is_no_relevant_information: 'There is no relevant information.',
		Ongoing_by: 'Ongoing by',
		Address: 'Address',
		Waiting: 'Waiting',
		Chat: 'Chat',
		MobileNumbe: 'Mobile Numbe',
		Provide_your_Date_of_Birth: 'Provide your Date of Birth',
		Enter_a_mobile_number: 'Enter a mobile number',
		Provide_a_debit_account: 'Provide a debit account',
		Please_fill_in_these_details_before_sending_an_offer: 'Please fill in these details before sending an offer',
		Reset: 'Reset',
		Delete: 'Delete',
		Payment: 'Payment',
		Budget: 'Budget',
		Location: 'Location',
		Details: 'Details',
		Please_fill_in_the_address: 'Please fill in the address',
		Workers: 'Workers',
		TotalFixPrice: 'Total Fix Price',
		Hourly: 'Hourly',
		EstimatedBudget: 'Estimated Budget',
		Person: 'Person',
		How_can_this_favor_be_completed: 'How can this favor be completed?',
		Offline: 'Offline',
		Country: 'Country',
		DueDate: 'Due Date',
		PayWithPayPal: 'Pay With PayPal',
		ApplePay: 'Apple Pay',
		Pay_from_income_balance: 'Pay from income balance',
		DifficultyLevel: 'Difficulty Level',
		UploadAttachments: 'Upload Attachments',
		Describe_your_favor: 'Describe your favor...',
		FavorDetails: 'Favor Details',
		Title_of_favor: 'Title of favor',
		FavorTitle: 'Favor Title',
		Communication: 'Communication',
		You_have_no_received_any_ratings: "You haven't received any ratings yet.",
		Last_name: 'Last name',
		First_name: 'First name',
		Birthday: 'Birthday',
		REQUEST_A_QUOTE: 'REQUEST A QUOTE',
		You_have_no_received_any_notifications_yet: 'You haven’t received any notifications yet.',
		APPLY_NOW: 'APPLY NOW',
		To: 'To',
		From: 'From',
		DateRange: 'Date Range',
		AfavorFee: 'Afavor Fee',
		Me: 'Me',
		ThisFavor: 'This Favor',
		Avaliable_for_withdrawal: 'Avaliable for withdrawal',
		Everything: 'Everything',
		There_is_no_content: 'There is no content.',
		You_have_no_favorite_helper: 'You have no favorite helper.',
		You_have_no_favorite_favor: 'You have no favorite favor.',
		Offer: 'Offer',
		Offers: 'Offers',
		Comments: 'Comments',
		Comment: 'Comment',
		Online: 'Online',
		TotalExpenditure: 'Total Expenditure',
		Price: 'Price',
		FavorEarnings: 'Favor Earnings',
		Completed_by: 'Completed by',
		online: 'online',
		Communication: 'Communication',
		WorkQuality: 'Work Quality',
		Punctuality: 'Punctuality',
		Ability: 'Ability',
		Leave_A_Comment: 'Leave a comment...',
		Difficulty: 'Difficulty',
		Attitude: 'Attitude',
		SUBMIT: 'SUBMIT',
		WorkEnvironment: 'Work Environment',
		SetAsDefaultDebitCart: 'Set as default debit card',
		Expenditure: 'Expenditure',
		Income: 'Income',
		REMOVE_CARD: 'REMOVE CARD',
		Loading: 'Loading...',
		AccountNumber: 'Account Number',
		PrivacyPolicy: 'Privacy Policy',
		TermsConditions: 'Terms & Conditions',
		YourEmailAddress: 'Your Email Address',
		Currency: 'Currency',
		youHaveNoReceivedAnyCommentsYet: "You haven't received any comments yet.",
		Make_A_Favor: 'Make a Favor',
		thankYouTip2: ',Your favor has been sent to poster.',
		thankYouTip: ',your favor has been posted.',
		GENDER: 'GENDER',
		GET_STARTED: 'GET STARTED',
		SKIP: 'SKIP',
		EnterVerificationCode: 'Enter verification code',
		forgetPawdTip: 'Please enter your account’s email address and we will send you a verification code.',
		confirmEmailTip: 'Please enter the verification code we just sent to your email.',
		AsAHelper2: 'As a Helper',
		AsAPoster2: 'As a Poster',
		Ratings: 'Ratings',
		MakePayments: 'Make Payments',
		ReceivePayments: 'Receive Payments',
		EditProfile: 'Edit Profile',
		Helper: 'Helper',
		Favors: 'Favors',
		DebitAccount: 'Debit Account',
		Analytics: 'Analytics',
		CreditCard: 'Credit Card',
		ADD_DEBIT_ACCOUNT: 'ADD DEBIT ACCOUNT',
		SaveCardDetails: 'Save Card Details',
		InsititutionNumber: 'Insititution Number',
		TransitNumber: 'Transit Number',
		AddNewDebitCard: 'Add New Debit Card',
		ADD_CREDIT_CARD: 'ADD CREDIT CARD',
		AddCreditCardTip: 'Afavor will maintain the confidentiality of your information',
		PostalCode: 'Postal Code',
		Province: 'Province',
		City: 'City',
		StreetAddress: 'Street Address',
		SecurityCode: 'Security Code',
		ExpireDate: 'Expire Date',
		Card_number: 'Card number',
		Name: 'Name',
		AddNewCreditCard: 'Add New Credit Card',
		Yes: 'Yes',
		No: 'No',
		AreYouSureToLogout: 'Are you sure to logout?',
		HowCanWeHelpYou: 'How can we help you?',
		SAVE: 'SAVE',
		CurrentPassword: 'Current Password',
		Language: 'Language',
		ChangePassword: 'Change Password',
		ViewAllReviews: 'View all Reviews',
		AsAHelper: 'As a Helper',
		AsAPoster: 'As a Poster',
		Skills: 'Skills',
		Verifications: 'Verifications',
		Reviews: 'Reviews',
		About: 'About',
		Open: 'Open',
		Ongoing: 'Ongoing',
		Completed: 'Completed',
		LogOut: 'Log out',
		ContactUs: 'Contact us',
		TermsPolicy: 'Terms & Policy',
		InviteFriends: 'Invite Friends',
		LOGIN: 'LOGIN',
		SIGN_UP: 'SIGN UP',
		SIGN_IN: "SIGN IN",
		Email: 'Email',
		Password: 'Password',
		ReEnterPassword: 'Re-enter Password',
		ForgotPassword: 'Forgot Password?',
		LoginWith: 'Login With',
		SignupWith: 'Sign up With',
		loginPolicy: 'By clicking Sign up you agree to our Terms of Service and Privacy Policy.',
		FIRST_NAME: 'FIRST NAME',
		LAST_NAME: 'LAST NAME',
		BIRTHDAY: 'BIRTHDAY',
		SEND: 'SEND',
		RESEND: 'RESEND',
		CONTINUE: 'CONTINUE',
		CONFIRM: 'CONFIRM',
		AvaliableFunds: 'Avaliable Funds',
		Notifications: 'Notifications',
		Revenue: 'Revenue',
		Ratings: 'Ratings',
		Favorites: 'Favorites',
		PaymentMethod: 'Payment Method',
		Settings: 'Settings',
		ThankYou: 'Thank You',
		NewPassword: 'New Password',
		ConfirmNewPassword: 'Confirm New Password',
		registerPolicy: 'By clicking Sign up you agree to our Terms of Service and Privacy Policy.',
		Male: 'Male',
		Female: 'Female',
		Discovering: 'Discovering',
		AllFavors: 'All Favors',
		browse: 'browse',
		Browse: 'Browse',
		Inbox: 'Inbox',
		inbox: 'inbox',
		Post: 'Post',
		post: 'post',
		My_Favors: 'My Favors',
		MyFavors: 'MyFavors',
		myFavors: 'myFavors',
		more: 'more',
		More: 'More'
	}
};

!function(window){
	var l = {
		change: function(){
			var language = $api.getStorage(CONFIG.KEY.LANGUAGE) || 1,
					_doms = $api.domAll('[lan]');

			language = language == 1 ? 'english' : 'french';

			[].forEach.call(_doms, function(dom, index){
				var _key = $api.attr(dom, 'lan');
				if(LANGUAGE[language][_key]){
					switch(dom.tagName){
						case 'INPUT':
						case 'TEXTAREA':
							$api.attr(dom, 'placeholder', LANGUAGE[language][_key]);
							break;
						default:
							$api.text(dom, LANGUAGE[language][_key]);
							break;
					}
				}
			});
		},
		init: function(args){
			var self = this;

			this.change();

			api.addEventListener({
				name: 'languageChange'
			}, function(ret){
				self.change();
			});
		}
	};

	window.L = l;
}(window);
